- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
- fedora_messaging/twisted/producer.py
I'm not pushing this right now because I think we need to have a discussion on what we want to do when a message can't be decoded or isn't JSON. Currently we just raise `ValidationError` which, I believe, crashes the consumer. Do we want to do a `basic_nack()` too? Do we want to log but ignore the message?
> Add tests for the consumer

- fedora_messaging/_session.py
0.12 adds the SSLOptions object, but it's got a different API than
1.0.0, and the old dictionary assignment still works. Just mark
SSLOptions as None if it's version 0.12 (this will break if there's a
0.13, but I don't think there will be).
> Modify check for pika TLS API

- fedora_messaging/cli.py
- fedora_messaging/config.py
Otherwise it may overwrite logging when the config object is used from
client applications.
> Don't automatically setup logging on config load

- fedora_messaging/message.py
Add a big red warning for developers to not override validate.
From the discussion on https://github.com/fedora-infra/fedora-messaging/pull/9
> Note that validate should not be overridden

- fedora_messaging/_session.py
- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
- fedora_messaging/tests/unit/test_session.py
- fedora_messaging/tests/unit/twisted/test_protocol.py
- fedora_messaging/twisted/protocol.py
I wonder if you think that would be a good idea. The Message class is already carrying the topic, I think it makes sense if the properties are stored there too.
One big plus: the `message_id` would be created on instantiation and would be always accessible, which is pretty cool to log when something goes wrong or to identify a message.
What do you think @jeremycline ?
> Have the Message class carry the properties as an attribute

- docs/messages.rst
- docs/sample_schema_package/mailman_schema/schema.py
- docs/sample_schema_package/mailman_schema/tests/test_schema.py
- docs/tutorial/schemas.rst
- fedora_messaging/_session.py
- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
- fedora_messaging/tests/unit/test_session.py
- fedora_messaging/twisted/protocol.py
Publishers shouldn't need to touch these after creation, and consumers
should not be digging in the raw JSON as this makes migrating from one
schema to another difficult. Instead, we should wrap the JSON object in
Python methods which form the public API of the message.
> Hide the JSON body and properties from users of messages

- docs/changelog.rst
- docs/consuming.rst
- docs/sample_schema_package/mailman_schema/tests/test_schema.py
- docs/tutorial/conversion.rst
- docs/tutorial/schemas.rst
- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
The ``summary`` method on the ``fedora_messaging.message.Message`` class
is now a property.
This came up during the Flock session so I thought it'd be good to get the change in ASAP and kick out a second alpha.
> Make the message summary a property

- fedora_messaging/cli.py
- fedora_messaging/config.py
- fedora_messaging/exceptions.py
- fedora_messaging/tests/fixtures/bad_conf.toml
- fedora_messaging/tests/fixtures/good_conf.toml
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/test_config.py
Also fix a small bug from exception changes in config.py
> Add tests for the CLI

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
- requirements.txt
The connection parameters need to set the credentials type to 'EXTERNAL'
in order for x509 client certificate authentication to work. Do so if
both the cert and key is present.
> Fix authentication with x509 certificates

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
Fix for throwing ChannelClosed exception by PublisherSession.publish
> Prevent PublisherSession.publish to throw ChannelClosed exception

- docs/api.rst
- docs/messages.rst
- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
Each message can now have a severity associated with it, both at a class
level and on a message-by-message basis.
> Add a severity to messages

- docs/fedora-messaging.rst
- fedora_messaging/cli.py
- fedora_messaging/tests/unit/test_cli.py
At the moment the only way to specify the AMQP URL is via the
configuration file. Until someone asks for the ability to specify it on
the CLI, just stick with that.
fixes #45
> Remove the unused --amqp-url parameter from the CLI

- requirements.txt
service_identity is an optional dependency of pyOpenSSL for users who
don't enjoy getting MITMed. Rather than leaving it up to the users to
just know this is an optional dependency they want, include it as a hard
requirement.
> Depend on service_identity for proper TLS client cert checking

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
> Remove the unused exchange parameter from the PublisherSession

- fedora_messaging/tests/unit/twisted/test_protocol.py
- fedora_messaging/twisted/protocol.py
- fedora_messaging/twisted/service.py
This allows users to bind to header exchanges, which provide routing
configuration via the bind arguments.
> Allow exchange type to be specified and pass on binding arguments

- dev-requirements.txt
- docs/changelog.rst
- docs/conf.py
- docs/contributing.rst
- fedora_messaging/__init__.py
- news/PR51.feature
- news/PR53.feature
- news/PR56.api
- news/PR63.feature
- news/PR65.api
- news/PR67.dev
- news/PR68.dev
- news/_template.rst
- news/aurelien.author
- news/get-authors.py
- news/jcline.author
- news/swojciechowski89.author
- pyproject.toml
- setup.py
Towncrier lets us generate release notes in a much more convenient way than what we currently do. Each PR just has to create a file with the line that should end up in the release notes, and the ``changelog.rst`` file can be automatically generated before each release.
I have added documentation in the ``contributing.rst`` file for more usage info.
@jeremycline I would also like you to verify that the releasing process I have documented in ``contributing.rst`` is correct, please.
> Use towncrier to generate the changelog

- fedora_messaging/_session.py
Since we require pika-0.12 and greater, this check is no longer
necessary.
> Drop compatibility code for pika-0.11

- .travis.yml
- fedora_messaging/tests/unit/twisted/test_protocol.py
- tox.ini
Add tests for pika 0.12 and 1.0.0 on both unit tests and integration
tests, and expand the integration test matrix for all Python versions.
fixes #53 
Note: I couldn't figure out how to get tox to run a different command for a sub-set of environments, thus the copy/paste :(
> Expand the test matrix for unit and integration tests

- fedora_messaging/cli.py
- news/PR86.feature
Click 7.x has a [different signature](https://click.palletsprojects.com/en/7.x/api/#click.BadOptionUsage) for the `BadOptionUsage` exception
> Compatibility with Click 7.x

- docs/index.rst
- docs/wire-format.rst
This includes a new section of documentation for users that wish to send
or receive messages using other libraries and languages.
> Document the wire format used by fedora-messaging

- README.rst
I noticed the docs badge in README.rst is showing failed docs even if they passed.
After looking at it more closely I noticed there is reference to wrong img.
Here is the fix for this.
> Fix docs badge

- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
Use the accessors to set message headers which cover the users and content
the message relates to.
Fixes #27
> Set headers for filtering

- fedora_messaging/_session.py
- fedora_messaging/config.py
- fedora_messaging/tests/unit/twisted/test_service.py
- fedora_messaging/twisted/service.py
For the sake of convenience, allow services to take a set of consumers
and have it pass them on to the factory.
> Add consumers to service init and pass to factory

- docs/tutorial/schemas.rst
- docs/wire-format.rst
- fedora_messaging/message.py
- fedora_messaging/tests/integration/test_publish_consume.py
- fedora_messaging/tests/unit/test_message.py
- news/PR89.api
When working on #88, I realized that using the class path as the unique
ID would be a bit odd when working from a different language. It seems
better to use the entry point name as the unique identifier.
> Use the entry point name as the unique identifier for schema

- docs/index.rst
- docs/testing.rst
- fedora_messaging/testing.py
- fedora_messaging/tests/unit/test_testing.py
I started moving anitya over to fedora-messaging, and quickly decided I
needed a helper for tests. Since this is generally useful, I thought
it'd be good to add it here and collect other things like this here.
> Start a module for test helpers

- fedora_messaging/message.py
- fedora_messaging/tests/unit/test_message.py
> Add abbility to serialize and deserialize messages

- config.toml.example
> Correct example callback in configuration

- fedora_messaging/api.py
- fedora_messaging/cli.py
- fedora_messaging/config.py
- fedora_messaging/tests/unit/test_api.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/test_config.py
In most production cases, there should be a configuration file with all the exchanges, queues, and bindings the application expects to be in place for a particular consumer or publisher. However, the CLI does offer some basic flags that should (in theory) be enough to make it work out of the box without touching a configuration file.
This fixes an issue with "fedora-messaging consume" where when you define a binding, you still need a configuration file with "queues" properly defined or it would do anything useful. Now, a basic queues dictionary is created by the CLI. To make this work, the ``consume`` API call needed to accept the queues argument, which it now does in the second commit in this series. I recommend reviewing this PR commit-by-commit.
> Make "fedora-messaging consume" useful without a config file

- dev-requirements.txt
Upstream is working on a fix[0], but until then this will let CI pass.
[0] https://github.com/pytest-dev/pytest-twisted/pull/45
> Temporarily pin pytest below 4.1 as it broke pytest-twisted

- fedora_messaging/cli.py
If a configuration file wasn't explicitly supplied, logging would not be
set up. Logging should be configured when running the CLI in all cases.
> Setup logging even when a configuration file isn't supplied

- fedora_messaging/cli.py
- fedora_messaging/tests/unit/test_cli.py
Make it clearer what action the user needs to take when a callback isn't
supplied, and where it came from if the setting isn't valid.
> Improve the error messages for invalid callback settings

- fedora_messaging/_session.py
- fedora_messaging/api.py
- fedora_messaging/tests/unit/test_session.py
- news/110.bug
Do you also want me to update docs?
> accept methods as callbacks as well

- fedora_messaging/config.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/test_config.py
The CLI test suite failed to reset the configuration after each test so some tests ran with different configurations. Fix up all those tests and make sure each test gets a fresh default config.
> Ensure CLI tests don't depend on each other

- docs/fedora-messaging.rst
- fedora_messaging/cli.py
- fedora_messaging/config.py
- fedora_messaging/tests/unit/test_cli.py
The command-line flags on the consume command are intended to make it
quick and easy to run simple consumers without fiddling with a
configuration file.
To this end, allow users to override --exchange, --queue-name, and
--routing-key, rather than requiring none or all. This brings it in line
with the manual page which states defaults for queue-name and exchange
will be used if they are not provided.
This implementation is simplistic in that it sets all bindings in the
configuration to be for the provided values. However, the command line
interface options do not offer a way exactly declare exchanges, queues,
and bindings (durability options, arbitrary arguments, etc) so the
documentation is updated to indicate for complex queue configurations,
the configuration file should be used instead …
>  Allow declaring --exchange/--queue-name/--routing-key independently

- docs/sample_schema_package/mailman_schema/schema.py
- docs/tutorial/schemas.rst
- fedora_messaging/message.py
- fedora_messaging/tests/integration/test_publish_consume.py
- fedora_messaging/tests/unit/test_message.py
- fedora_messaging/tests/unit/test_session.py
- news/PR119.api
The message `body` property should be public, otherwise schema writers will have to write an accessor for each dictionary entry, which does not make much sense.
> Make the message body a public property

- docs/sample_schema_package/mailman_schema/schema.py
- docs/sample_schema_package/mailman_schema/tests/test_schema.py
The message ``body`` variable is used by the Message class, but the
example schema is still defining a property using that name.
See https://pagure.io/fedora-commops/fedora-happiness-packets/issue/96
> Fix the mailman_schema example to work with Message.body

- dev-requirements.txt
- docs/api.rst
- docs/fedora-messaging.rst
- fedora_messaging/api.py
- fedora_messaging/cli.py
- fedora_messaging/exceptions.py
- fedora_messaging/tests/integration/test_cli.py
- fedora_messaging/tests/integration/test_twisted_api.py
- fedora_messaging/tests/unit/test_api.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/twisted/test_factory.py
- fedora_messaging/tests/unit/twisted/test_protocol.py
- fedora_messaging/tests/unit/twisted/test_service.py
- fedora_messaging/twisted/consumer.py
- fedora_messaging/twisted/factory.py
- fedora_messaging/twisted/protocol.py
- fedora_messaging/twisted/service.py
- news/PR139.feature
- requirements.txt
This adds two new APIs to fedora-messaging:
1. twisted_consume() provides a way for users to start AMQP consumers that
run until explicitly canceled or until a fatal error occurs on the
broker.
2. twisted_cancel_consume() stops consumers started by
twisted_consume().
This introduces new versions of the Protocol, Factory, and Service
classes as the APIs of these Twisted classes had to change. The original
classes have been deprecated and will be removed in fedora-messaging
v2.0.0.
Note: this is currently a work-in-progress - documentation and a few more tests are required. I'm just making sure the Ubuntu-based CI is passing with the new integration tests.
> Add Twisted consume APIs

- docs/tutorial/installation.rst
This PR adds pointers for installing fedora-messaging and setting up RabbitMQ in dockerised applications
as suggested by @jeremycline [here](https://pagure.io/fedora-commops/fedora-happiness-packets/issue/96#comment-558547) in the tutorial docs.
> [Docs] Add instructions for installing the library and RabbitMQ in Docker

- fedora_messaging/twisted/factory.py
This makes it look more useful when it is logged or printed during
debugging. Before, Twisted emitted the following log:
Starting factory
<fedora_messaging.twisted.factory.FedoraMessagingFactoryV2 object at
0x7f9aa4d4d358>
With this change, the log message becomes:
Starting factory FedoraMessagingFactoryV2(parameters=<URLParameters
host=rabbitmq.stg.fedoraproject.org port=5671
virtual_host=/public_pubsub ssl=True>, confirms=True)
which is much more helpful.
> Add __repr__ implementations to the Twisted factory

- fedora_messaging/tests/unit/twisted/test_factory.py
Test coverage was not included in #150, add coverage here to make sure
things like passwords don't get logged.
> Add test for the Factory __repr__ function

- fedora_messaging/api.py
- fedora_messaging/cli.py
- fedora_messaging/exceptions.py
- fedora_messaging/tests/integration/test_cli.py
- fedora_messaging/tests/integration/test_twisted_api.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/twisted/consumer.py
- fedora_messaging/twisted/factory.py
- fedora_messaging/twisted/protocol.py
There are a number of cases which weren't being properly handled on the
less-than-happy path for authentication:
1. If the user had no access to the vhost at all, it would endlessly
reconnect without any indication of a problem.
2. If authentication failed, it would do the same thing as 1.
3. If the user had access to the vhost, but lacked read permissions, it
would set up the queue, configure the subscriber, and then would fail
to read from the queue. The channel would be closed and it would
assume it was a connection problem, but the connection was fine. The
consumer would just hang.
For 1 and 2, a ConnectionException is now raised by ``twisted_consume``
as the connection is not going to improve with more retries.
For 3, a new exception has been added, PermissionException (of which …
> Add better error handling for permission denied cases

- requirements.txt
Twisted doesn't depend on PyOpenSSL, but its ssl module does use it. Add
it as an explicit dependency.
> Add PyOpenSSL to the dependency list

- docs/fedora-broker.rst
With a single ugly sed command, users can create their own configuration
file. Add a set of instructions into the broker documentation so folks
can just copy/paste while experimenting.
> Add some copy/paste commands for getting connected

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/test_session.py
If there's any channel or connection problem and we don't reset the
channel and connection, the next call to publish will fail with
something like a ChannelWrongStateError, so handle any ChannelError by
resetting everything.
This switches the exception handling order since NackError and company
are specific subclasses of AMQPChannelErrors and we handle those two
differently.
>  Handle general connection/channel exceptions when publishing 

- fedora_messaging/api.py
- fedora_messaging/cli.py
- fedora_messaging/tests/integration/test_twisted_api.py
- fedora_messaging/tests/unit/test_cli.py
- fedora_messaging/tests/unit/twisted/test_protocol.py
- fedora_messaging/twisted/protocol.py
Add a documentation note for the PermissionException, a test, and handle
it in the CLI. See https://github.com/pika/pika/pull/1202 for the pika
issue.
> Handle Pika 1.0.1+ consume permission exception

- fedora_messaging/cli.py
- fedora_messaging/tests/fixtures/bad_cb
- fedora_messaging/tests/fixtures/callback.py
- fedora_messaging/tests/unit/test_cli.py
- news/159.feature
Previously, the callback needed to reside on the Python Path, which is
convenient if you're already making a Python package. Plenty of folks
aren't, though, so allow users to provide a file that we'll boldly exec
and load a callback from.
Fixes #159
Note: I added this as a new option since I was concerned about messing up distinguishing the filesystem path from the Python path cases. This way the user is explicit, at the expense of things not quite Just Working. Feedback welcome on that decision.
> Add a "--callback-file" option

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
Previously publishing was only retried if the connection was closed
cleanly. However, it might close for other reasons (someone trips over a
cord, a firewall kills a connection, etc). We should go through the
retry process for any connection exception.
Fixes #175
> Retry publishing for all connection-related errors

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
If a generic AMQP error occurs, do not try to re-use the connection. The
channel and connection has likely been closed because this is usually
due to protocol-level issues.
> Reset the connection and channel for AMQP errors

- docs/api.rst
- docs/consuming.rst
- docs/messages.rst
- fedora_messaging/message.py
This expands the message API documentation and adds a table of content
to the top of the API docs, separating each function or class with a
sub-header. It should provide a high level overview of the complete API
at a glance, and fleshes out some of the API documentation that was
lacking in the Message class.
Fixes: #164
Fixes: #166
> Improve the readability of the API documentation

- docs/consuming.rst
A number of users did not find the section on using a class as a
callback. This attempts to re-organize the documentation around the
consumer API to make it clearer.
@dustymabe, @bowlofeggs, it'd be great if you could skim this and let me know if it's clearer.
> Re-organize the consuming documentation for clarity

- .travis.yml
- docs/conf.py
- docs/contributing.rst
- fedora_messaging/_session.py
- fedora_messaging/tests/integration/test_publish_consume.py
- fedora_messaging/tests/integration/test_twisted_api.py
- fedora_messaging/tests/unit/test_session.py
- fedora_messaging/tests/unit/twisted/test_protocol.py
- fedora_messaging/twisted/protocol.py
- requirements.txt
- setup.py
- tox.ini
- travis-integration-setup.sh
Drop Python 3.4 and 3.5 from the CI configuration and mark Python 3.6 as
the lowest Python 3 version supported. EPEL7 has a Python 3.6 stack now.
This unfortunately expanded a bit because the CI was also broken due to Travis moving to Xenial by default and not installing RabbitMQ on those *and* because Six moved its docs. I went ahead and also dropped the Pika 0.x matrix because 1.0+ is available everywhere we care about.
> Drop official Python 3.4 and 3.5 support

- docs/api.rst
- fedora_messaging/config.py
The config docs mention these, but they have not be officially
documented as part of the API. Include them.
> Add the "conf" and "DEFAULTS" variables to the API documentation

- configs/fedora.toml
This is based on my experience porting several fedmsg consumers
to fedora-messaging. @jcline thought it would be good for
consumers to provide more useful info in client_properties, so
I invented a couple of optional fields there. Also you need a
second binding to receive messages from the ZMQ->AMQP bridge
(which most consumers are likely to want to do), and it seems
useful to note that if your consumer implements a logger, it
needs to be configured here or else messages won't show up.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
> Update example config: ZMQ exchange, extra properties, logging

- fedora_messaging/_session.py
- fedora_messaging/tests/unit/test_session.py
The CLI (by way of Twisted) does not declare exchanges when consuming,
it assumes the exchange already exists. This seems reasonable, consumers
will still learn about configuration mistakes during the binding
process. This makes it impossible to consume from the public vhost in
Fedora, so this is a quick bugfix release while the transition to
Crochet and Twisted are worked on and polished.
Fixes: #171
> Don't declare exchanges when consuming

- docs/sample_schema_package/MANIFEST.in
- docs/sample_schema_package/setup.py
This commit adds the following for the Sample Schema package (as discussed with @jeremycline): 
1. A MANIFEST.in that includes non-code files and test package
2. Not exclude the test package in setup.py
> Add MANIFEST.in and include tests for sample schema package

- fedora_messaging/tests/unit/twisted/test_factory.py
- fedora_messaging/twisted/factory.py
- fedora_messaging/twisted/protocol.py
We currently have unformatted logs, like: `Stopping AMQP consumer {tag} for queue {q}: {e}`. This commit fixes it.
> Twisted legacy logging does not accept format parameters

- docs/quick-start.rst
The previous wording made it sound like it was deleted after an hour of
use.
> Clarify queues are only deleted if unused

- fedora_messaging/tests/unit/twisted/test_factory.py
- fedora_messaging/twisted/factory.py
- news/208.bug
Reconnecting twice in a row would trigger an `AlreadyCalledError` on the `_client_deferred` Deferred.
> Fix a reconnection issue

- fedora_messaging/tests/unit/twisted/test_factory.py
- fedora_messaging/twisted/factory.py
This also alters the logging of general errors to capture the actual failure rather than the StopIteration exception from the inline callback generator.
> Handle ConnectionLost errors in the on_ready errbacks

- fedora_messaging/api.py
- fedora_messaging/tests/integration/test_api.py
- fedora_messaging/twisted/factory.py
- news/212.bug
When a `PublishTimeout` occurs, the `_client_deferred` is cancelled but it was not renewed, as it is in other cases.
Fixes: #212
> Fix handling of new connections after a publish timeout

- fm-consumer@.service
Consumers using the fm-consumer@ service pattern are quite
vulnerable to a problem where, for instance, consuming a message
fails because some key service the consumer needs to talk to is
down. When this happens, the service is considered to have
failed, and - because Restart=on-failure is set - is immediately
(well, after 100ms) restarted. It then immediately attempts to
consume the same message, and - because the service likely
didn't come up in the last 100ms - probably fails again. This
continues to happen in a very fast cycle. If the consumer times
out quite quickly and the service stays down for several hours,
you can easily accumulate a loop of tens of thousands of
failures. This pollutes the system journal quite badly and is
a nightmare if you have the consumer configured to email …
> Only try to restart fm-consumer@ services every 60 seconds

- dev-requirements.txt
Tests started failing the same day Pytest made a release. I can't be
bothered to set up a development environment again so I'm making this PR
to test the theory.
> Pytest 5.4 breaks the Twisted tests
