fedora-infra/fedora-messaging

docs/conf.py, docs/contributing.rst, tox.ini
Slightly more welcoming than an empty page
=> Add initial contribution documentation 

docs/messages.rst, docs/sample_schema_package/LICENSE, docs/sample_schema_package/README, docs/sample_schema_package/mailman_schema/__init__.py, docs/sample_schema_package/mailman_schema/schema.py, docs/sample_schema_package/mailman_schema/tests/__init__.py, docs/sample_schema_package/mailman_schema/tests/test_schema.py, docs/sample_schema_package/setup.cfg, docs/sample_schema_package/setup.py
=> Add a sample message schema Python package with documentation

docs/publishing.rst, fedora_messaging/_session.py, fedora_messaging/message.py, fedora_messaging/tests/unit/test_message.py, fedora_messaging/tests/unit/test_session.py
Remove the schema version, it's useless now.
=> Schema version

README.rst
Include a quick introduction to the library and links to more
information. Also more badges.
=> Flesh out the README a bit

config.toml.example, fedora_messaging/_session.py
Use the double-brackets syntax.
=> Use a simpler config syntax for bindings

docs/api.rst, docs/conf.py, docs/index.rst, docs/sample_schema_package/mailman_schema/schema.py, docs/sample_schema_package/mailman_schema/tests/test_schema.py, docs/sample_schema_package/setup.py, docs/tutorial/conversion.rst, docs/tutorial/exceptions.rst, docs/tutorial/index.rst, docs/tutorial/installation.rst, docs/tutorial/schemas.rst, docs/tutorial/usage.rst, fedora_messaging/api.py, fedora_messaging/exceptions.py
This branch adds a tutorial that we'll be able to use in the Flock workshop.
=> Add tutorial

setup.py
Signed-off-by: Miroslav Suchý <msuchy@redhat.com>
=> add url to setup.py

fedora_messaging/tests/integration/test_publish_consume.py
With an old checkout I noticed initial connection failures raised the
wrong exception because the connection could be None. That got fixed in
commit ab832374c3fd. This adds a quick test for that fix.
=> Add integration test for refused connections

docs/sample_schema_package/mailman_schema/schema.py, docs/sample_schema_package/mailman_schema/tests/test_schema.py, docs/sample_schema_package/mailman_schema/utils.py, docs/sample_schema_package/setup.cfg, fedora_messaging/message.py, fedora_messaging/tests/unit/test_message.py
=> Add accessors on the Message class

.mergify.yml, CODEOWNERS
Signed-off-by: Clement Verna <cverna@tutanota.com>
=> Add mergify config to allow automatic merge when a PR has been approved.

fedora_messaging/tests/unit/twisted/test_protocol.py, fedora_messaging/twisted/protocol.py
Fixes: #34 (but only partially)
=> Handle pika 0.12 better

fedora_messaging/message.py, fedora_messaging/tests/unit/test_message.py, requirements.txt
=> Add a timezone to sent-at headers

codecov.yml, tox.ini
Set patch coverage to 100% and project coverage to the current value.
=> Add coverage requirements

fedora_messaging/tests/unit/twisted/test_service.py, fedora_messaging/twisted/service.py
Create the connection with a client certificate, if configured to do so.
@abompard As an aside, what do you think about taking something like this and getting it into upstream pika? It seems like if the SSL context has client certs set, we should automatically be a) setting auth to EXTERNAL, and b) producing the correct twisted connection parameters from the pika parameters.
=> Add support for client x509 authentication in Twisted

docs/consuming.rst, fedora_messaging/_session.py, fedora_messaging/exceptions.py, fedora_messaging/tests/unit/test_session.py
=> Allow consumers to requeue messages when Halting and document it

fedora_messaging/api.py
=> Add info about api.consume throwing ValueError

fedora_messaging/cli.py, fedora_messaging/tests/unit/test_cli.py
Any hints/tips/corrections related to my work are welcome.
=> add unittests for cli consume

fedora_messaging/config.py
=> change queue name in config doc

docs/api.rst, docs/tutorial/schemas.rst, docs/tutorial/usage.rst
=> Add a section in the tutorial for severity

fedora_messaging/api.py, fedora_messaging/message.py
It's nice to be able to iterate through valid severities or to check if
a severity is a valid one.
=> Add a SEVERITIES constant with list valid severities

fedora_messaging/api.py, fedora_messaging/tests/unit/test_api.py
=> unittests for api

.license_strategy.ini, .travis.yml, tox.ini
Check that our dependencies have Free licenses.
=> Check dependencies' licenses

docs/installation.rst
=> Update the Fedora installation docs

docs/sample_schema_package/setup.py
=> Add mailman_schema classes to setup.py entry_points

docs/sample_schema_package/setup.py
All unittests passed on my python 3.7 environment.
=> Add python3.7 classifier to mailman_schema

fedora_messaging/tests/unit/test_session.py
=> Add unittests for _session.ConsumerSession

.coveragerc, dev-requirements.txt, tox.ini
This also tries to fix up the coverage reporting, but I'm not actually sure what the problem is with that so... I dunno.
=> Simply the test matrix in tox

news/get-authors.py
Only small update for get-authors.py script.
This will check git log only from last tag.
=> Only get changelog authors from last tag

fedora_messaging/message.py
=> Add info about message.get message raising ValidationError

fedora_messaging/message.py, fedora_messaging/tests/unit/test_message.py
=> Add accessors for containers, modules, and flatpaks

fedora_messaging/tests/unit/twisted/test_factory.py, fedora_messaging/twisted/protocol.py, news/97.bug
=> Fix a compatibility issue between pika 0.12 and 1.0

docs/changelog.rst, fedora_messaging/__init__.py, fedora_messaging/_session.py, fedora_messaging/cli.py, fedora_messaging/twisted/protocol.py
=> Prepare v1.1.0

docs/consuming.rst, fedora_messaging/cli.py, fedora_messaging/tests/fixtures/good_conf.toml, fedora_messaging/tests/unit/test_cli.py
=> Correct cli consume bindings parameters

docs/api.rst, fedora_messaging/schema_utils.py, fedora_messaging/tests/unit/test_schema_utils.py, news/PR108.feature
At the moment it's mostly functions to generate avatar URLs.
=> Add utilities for message schemas

docs/fedora-messaging.rst, fm-consumer@.service
Add some documentation to create a systemd service file based on the `consume` subcommand.
=> Add a consumer systemd service file

.travis.yml, fedora_messaging/_session.py, fedora_messaging/tests/unit/test_session.py, fedora_messaging/tests/unit/twisted/test_protocol.py, fedora_messaging/twisted/protocol.py, news/126.feature, tox.ini
This adds support for Pika 0.13, and all Pika 0.x versions.
=> Support Pika 0.13

config.toml.example, fedora_messaging/config.py, fedora_messaging/message.py, fedora_messaging/tests/unit/test_config.py, fedora_messaging/tests/unit/test_message.py, news/121.feature
=> Add a configurable way to prefix the topic

.mergify.yml
Signed-off-by: Michal Konečný <mkonecny@redhat.com>
=> Update mergify to v2

fedora_messaging/config.py, fedora_messaging/tests/unit/test_config.py, readthedocs.txt, requirements.txt
Fixes: #132
Signed-off-by: Aurélien Bompard <aurelien@bompard.org>
=> Use toml instead of pytoml

fedora_messaging/_session.py, fedora_messaging/config.py, fedora_messaging/tests/unit/test_config.py, fedora_messaging/tests/unit/test_session.py, fedora_messaging/tests/unit/twisted/test_factory.py, fedora_messaging/twisted/protocol.py, news/136.feature
Feel free to edit this PR @jeremycline .
=> Support passive declares

fedora_messaging/message.py, fedora_messaging/tests/unit/test_message.py, fedora_messaging/tests/unit/test_session.py
=> Only prepend the topic_prefix on outgoing messages

docs/changelog.rst, fedora_messaging/__init__.py, news/PR139.feature
=> Generate the changelog for v1.6.0 and bump the library version

dev-requirements.txt
=> Unpin pytest as it works with pytest-twisted now

docs/changelog.rst, fedora_messaging/__init__.py
=> Write the changelog for 1.6.1 and bump the version

fedora_messaging/config.py
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>
=> Document that logging is only set up for consumers

configs/fedora.stg.toml
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Make same example config changes in the staging example

docs/consuming.rst, docs/tutorial/usage.rst
Some users are hitting issues and aren't aware that logging needs to be
configured. Add a note to the consuming snippets about setting up
logging.
See #190 and the issues mentioned in the comment.
=> Document a quick way to setup logging

docs/wire-format.rst, fedora_messaging/tests/unit/test_example.py
Thanks to @AdamWill  for noticing.
=> Document the sent-at header in messages

fedora_messaging/config.py
Adam Williamson added these to the config examples. Document them in the
configuration documentation as well.
=> Note the addition client properties in the config docs

docs/changelog.rst, fedora_messaging/__init__.py, news/208.bug, news/PR43.feature
=> Version 2.0.0

docs/changelog.rst, docs/tutorial/exceptions.rst, fedora_messaging/api.py
Fixes #215
I'd like your opinion on my wording if possible, @jeremycline.
=> Fix the docs about exceptions being wrapped by HaltConsumer
